apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: investment-committee
  labels:
    app: backend
    app.kubernetes.io/name: the-investment-committee
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app: backend
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
