apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: investment-committee
  labels:
    app: frontend
    app.kubernetes.io/name: the-investment-committee
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
