apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: investment-committee

resources:
  - namespace.yaml
  - configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: the-investment-committee
      app.kubernetes.io/managed-by: kustomize

