apiVersion: v1
kind: Namespace
metadata:
  name: investment-committee
  labels:
    app.kubernetes.io/name: the-investment-committee
    app.kubernetes.io/part-of: the-investment-committee
    app.kubernetes.io/managed-by: kustomize
